sonar.projectKey=techstore
sonar.projectName=TechStore E-Commerce
sonar.projectVersion=1.0

sonar.sources=.
sonar.language=py
sonar.sourceEncoding=UTF-8

# Test ve sanal ortam dizinleri hariç
sonar.exclusions=venv/**,tests/**,**/__pycache__/**,*.pyc

# Test kapsamı raporu
sonar.python.coverage.reportPaths=coverage.xml

# Kalite kapısı eşiği
sonar.qualitygate.wait=true
